# Generated by Django 5.0.4 on 2024-04-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='featured',
            field=models.BooleanField(blank=True),
        ),
    ]
