# Generated by Django 5.0.4 on 2024-04-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_alter_book_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
        migrations.AddField(
            model_name='book',
            name='BookCover',
            field=models.ImageField(null=True, upload_to='jpg'),
        ),
        migrations.AddField(
            model_name='book',
            name='BorrowingPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000),
        ),
        migrations.AddField(
            model_name='book',
            name='TheBook',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000),
        ),
    ]
