# Generated by Django 5.0.4 on 2024-04-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_remove_book_summary_book_bookcover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='BookCover',
        ),
        migrations.RemoveField(
            model_name='book',
            name='TheBook',
        ),
    ]
