# Generated by Django 5.0.4 on 2024-04-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_remove_book_bookcover_remove_book_thebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='BookCover',
            field=models.ImageField(null=True, upload_to='jpg'),
        ),
        migrations.AddField(
            model_name='book',
            name='TheBook',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
