# Generated by Django 5.0.4 on 2024-05-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_book_bookcover_book_thebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='BookCover',
            field=models.ImageField(null=True, upload_to='media/jpg'),
        ),
        migrations.AlterField(
            model_name='book',
            name='TheBook',
            field=models.FileField(null=True, upload_to='media/pdfs'),
        ),
    ]
