# Generated by Django 5.0.4 on 2024-05-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0009_signup_alter_book_bookcover_alter_book_thebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
