# Generated by Django 5.0.4 on 2024-05-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0012_remove_profile_bio_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='media/ProfilePic'),
        ),
    ]
